
CREATE TABLE USUARIO (
                ID_USUARIO BIGINT IDENTITY NOT NULL,
                CPF VARCHAR(11) NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                SENHA VARCHAR(20) NOT NULL,
                CONSTRAINT USUARIO_pk PRIMARY KEY (ID_USUARIO)
)
CREATE UNIQUE  NONCLUSTERED INDEX USUARIO_idx
 ON USUARIO
 ( CPF )


CREATE TABLE FORMACAO (
                ID_FORMACAO BIGINT IDENTITY NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                PONTO BIGINT NOT NULL,
                CONSTRAINT FORMACAO_pk PRIMARY KEY (ID_FORMACAO)
)
CREATE UNIQUE  NONCLUSTERED INDEX FORMACAO_idx
 ON FORMACAO
 ( PONTO )

CREATE UNIQUE  NONCLUSTERED INDEX FORMACAO_idx1
 ON FORMACAO
 ( NOME )


CREATE TABLE CURSO (
                ID_CURSO BIGINT IDENTITY NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                CONSTRAINT CURSO_pk PRIMARY KEY (ID_CURSO)
)
CREATE UNIQUE  NONCLUSTERED INDEX CURSO_idx
 ON CURSO
 ( NOME )


CREATE TABLE PESSOA (
                ID_PESSOA BIGINT IDENTITY NOT NULL,
                ID_CURSO BIGINT NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                OBSERVACAO VARCHAR(1000),
                ID_USUARIO BIGINT NOT NULL,
                CONSTRAINT PESSOA_pk PRIMARY KEY (ID_PESSOA)
)
CREATE UNIQUE  NONCLUSTERED INDEX PESSOA_idx
 ON PESSOA
 ( NOME )


CREATE TABLE PESSOA_FORMACAO (
                ID_FORMACAO BIGINT NOT NULL,
                ID_PESSOA BIGINT NOT NULL,
                CONSTRAINT PESSOA_FORMACAO_pk PRIMARY KEY (ID_FORMACAO, ID_PESSOA)
)

ALTER TABLE PESSOA ADD CONSTRAINT USUARIO_PESSOA_fk
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PESSOA_FORMACAO ADD CONSTRAINT ID_FORMACAO_PESSOA_FORMACAO_fk
FOREIGN KEY (ID_FORMACAO)
REFERENCES FORMACAO (ID_FORMACAO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PESSOA ADD CONSTRAINT CURSO_PESSOA_fk
FOREIGN KEY (ID_CURSO)
REFERENCES CURSO (ID_CURSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PESSOA_FORMACAO ADD CONSTRAINT PESSOA_PESSOA_FORMACAO_fk
FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA (ID_PESSOA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

